/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import type { GetNearbyPlacesParams, GetVisitedPlaceMarkersParams } from '@/features/map/api/dto';

export const getGetNearbyPlacesQueryKey = (params?: GetNearbyPlacesParams) => {
  return [`/recommendations/nearby-places`, ...(params ? [params] : [])] as const;
};

export const getGetVisitedPlaceMarkersQueryKey = (params?: GetVisitedPlaceMarkersParams) => {
  return [`/consumptions/visited-places`, ...(params ? [params] : [])] as const;
};
