/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useQuery, useSuspenseQuery } from '@tanstack/react-query';

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType } from '@/shared/apis/orvalMutator';

import type {
  GetNearbyPlacesParams,
  GetVisitedPlaceMarkersParams,
  SecondParameter,
} from '@/features/map/api/dto';

import { getNearbyPlaces, getVisitedPlaceMarkers } from '@/features/map/api/clients';

import {
  getGetNearbyPlacesQueryKey,
  getGetVisitedPlaceMarkersQueryKey,
} from '@/features/map/api/queryKeys';

export const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetNearbyPlacesQueryOptions = <
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNearbyPlacesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNearbyPlaces>>> = ({ signal }) =>
    getNearbyPlaces(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNearbyPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNearbyPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof getNearbyPlaces>>>;

export type GetNearbyPlacesQueryError = ErrorType<unknown>;

export function useGetNearbyPlaces<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyPlaces>>,
          TError,
          Awaited<ReturnType<typeof getNearbyPlaces>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetNearbyPlaces<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyPlaces>>,
          TError,
          Awaited<ReturnType<typeof getNearbyPlaces>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetNearbyPlaces<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 내 주변 가게 추천
 */

export function useGetNearbyPlaces<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNearbyPlacesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetNearbyPlacesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNearbyPlacesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNearbyPlaces>>> = ({ signal }) =>
    getNearbyPlaces(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getNearbyPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNearbyPlacesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNearbyPlaces>>
>;

export type GetNearbyPlacesSuspenseQueryError = ErrorType<unknown>;

export function useGetNearbyPlacesSuspense<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetNearbyPlacesSuspense<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetNearbyPlacesSuspense<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 내 주변 가게 추천
 */

export function useGetNearbyPlacesSuspense<
  TData = Awaited<ReturnType<typeof getNearbyPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: GetNearbyPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNearbyPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNearbyPlacesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetVisitedPlaceMarkersQueryOptions = <
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVisitedPlaceMarkersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>> = ({ signal }) =>
    getVisitedPlaceMarkers(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVisitedPlaceMarkersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVisitedPlaceMarkers>>
>;

export type GetVisitedPlaceMarkersQueryError = ErrorType<unknown>;

export function useGetVisitedPlaceMarkers<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetVisitedPlaceMarkersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
          TError,
          Awaited<ReturnType<typeof getVisitedPlaceMarkers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVisitedPlaceMarkers<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
          TError,
          Awaited<ReturnType<typeof getVisitedPlaceMarkers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVisitedPlaceMarkers<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 홈 화면 지도용 방문 장소 마커 조회
 */

export function useGetVisitedPlaceMarkers<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVisitedPlaceMarkersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetVisitedPlaceMarkersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVisitedPlaceMarkersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>> = ({ signal }) =>
    getVisitedPlaceMarkers(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVisitedPlaceMarkersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVisitedPlaceMarkers>>
>;

export type GetVisitedPlaceMarkersSuspenseQueryError = ErrorType<unknown>;

export function useGetVisitedPlaceMarkersSuspense<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetVisitedPlaceMarkersParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVisitedPlaceMarkersSuspense<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetVisitedPlaceMarkersSuspense<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 홈 화면 지도용 방문 장소 마커 조회
 */

export function useGetVisitedPlaceMarkersSuspense<
  TData = Awaited<ReturnType<typeof getVisitedPlaceMarkers>>,
  TError = ErrorType<unknown>,
>(
  params?: GetVisitedPlaceMarkersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getVisitedPlaceMarkers>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetVisitedPlaceMarkersSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
