/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type { BodyType } from '@/shared/apis/orvalMutator';

import type {
  AccountUpdateRequest,
  ApiResponseAccountResponse,
  ApiResponseVoid,
  SecondParameter,
} from '@/features/my-page/api/dto';

/**
 * Access Token으로 인증된 사용자의 기본 정보를 조회합니다.
 * @summary 내 정보 조회
 */
export const getMyAccount = (options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
  return apiClient<ApiResponseAccountResponse>(
    { url: `/accounts/me`, method: 'GET', signal },
    options
  );
};

/**
 * Kakao는 연결 해제와 회원 탈퇴를 즉시 처리하고 200 OK를 반환합니다.
 *
 * Google은 202 Accepted와 Location 헤더를 반환하며, 클라이언트가 해당 URI로 이동해 재인증을 완료하면 callback에서 회원 탈퇴를 처리합니다.
 *
 * Google의 202 Accepted 응답은 회원 탈퇴 완료를 의미하지 않습니다.
 *
 * 회원 탈퇴 완료 후 WEB과 APP은 보관 중인 Access Token을 삭제해야 합니다.
 *
 * WEB은 Refresh Token 쿠키가 만료되며, APP은 로컬에 저장된 Refresh Token도 함께 삭제해야 합니다.
 * @summary 회원 탈퇴
 */
export const withdrawMyAccount = (
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseVoid>({ url: `/accounts/me`, method: 'DELETE', signal }, options);
};

/**
 * 닉네임과 프로필 이미지를 선택적으로 수정합니다.
 *
 * - `profileImage` 전달: 프로필 이미지를 등록하거나 교체합니다.
 * - `deleteProfileImage=true`: 기존 프로필 이미지를 삭제합니다.
 * - 이미지 관련 값을 전달하지 않으면 기존 프로필 이미지를 유지합니다.
 * - 이미지 파일과 삭제 요청은 동시에 사용할 수 없습니다.
 * @summary 내 정보 수정
 */
export const updateMyAccount = (
  accountUpdateRequest?: BodyType<AccountUpdateRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  if (accountUpdateRequest?.nickname !== undefined && accountUpdateRequest.nickname !== null) {
    formData.append(`nickname`, accountUpdateRequest.nickname);
  }
  if (
    accountUpdateRequest?.profileImage !== undefined &&
    accountUpdateRequest.profileImage !== null
  ) {
    formData.append(`profileImage`, accountUpdateRequest.profileImage);
  }
  if (accountUpdateRequest?.deleteProfileImage !== undefined) {
    formData.append(`deleteProfileImage`, accountUpdateRequest.deleteProfileImage.toString());
  }

  return apiClient<ApiResponseAccountResponse>(
    {
      url: `/accounts/me`,
      method: 'PATCH',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  );
};
