/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type {
  ApiResponsePlaceDetailResponse,
  ApiResponsePlaceLikeResponse,
  ApiResponsePlaceVisitScrollResponse,
  GetPlaceVisitsParams,
  SecondParameter,
} from '@/features/shop/apis/dto';

/**
 * 좋아요 상태를 등록하고 취소한다
 * @summary 가게 좋아요 토글
 */
export const toggleLike = (
  placeId: number,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponsePlaceLikeResponse>(
    { url: `/places/${placeId}/likes`, method: 'PUT', signal },
    options
  );
};

/**
 * 장소 정보, 단골(isRegular) 여부, 방문 통계, 스티커 정보를 조회합니다. 페이지네이션 없음.
 * @summary 장소 상세 조회
 */
export const getPlaceDetail = (
  placeId: number,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponsePlaceDetailResponse>(
    { url: `/consumptions/places/${placeId}`, method: 'GET', signal },
    options
  );
};

/**
 * 장소 하나로 좁혀진 방문 이력을 최신순 커서 기반으로 조회합니다(월 제한 없음). nextCursorPurchaseDate/nextCursorPurchaseTime/nextCursorId를 다음 요청에 넣어 보내면 됩니다.
 * @summary 장소별 방문 이력 무한스크롤 조회
 */
export const getPlaceVisits = (
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponsePlaceVisitScrollResponse>(
    { url: `/consumptions/places/${placeId}/visits`, method: 'GET', params, signal },
    options
  );
};
