/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

export type PlaceLikeResponse = {
  liked?: boolean;
};

export type ApiResponsePlaceLikeResponse = {
  code?: string;
  message?: string;
  data?: PlaceLikeResponse;
};

export type StatsResponse = {
  firstVisitedDate?: string;
  monthlyVisitCount?: number;
  totalVisitCount?: number;
  totalVisitComment?: string;
};

export type RecentStickerResponse = {
  itemName?: string;
  receivedAt?: string;
};

export type StickerSummaryResponse = {
  itemName?: string;
  count?: number;
};

export type PlaceDetailResponse = {
  placeId?: number;
  placeName?: string;
  category?: string;
  address?: string;
  isRegular?: boolean;
  stats?: StatsResponse;
  recentStickers?: RecentStickerResponse[];
  stickerSummary?: StickerSummaryResponse[];
};

export type ApiResponsePlaceDetailResponse = {
  code?: string;
  message?: string;
  data?: PlaceDetailResponse;
};

export type PlaceVisitResponse = {
  visitedAt?: string;
  amount?: number;
};

export type PlaceVisitScrollResponse = {
  visits?: PlaceVisitResponse[];
  hasNext?: boolean;
  nextCursorPurchaseDate?: string;
  nextCursorPurchaseTime?: string;
  nextCursorId?: number;
};

export type ApiResponsePlaceVisitScrollResponse = {
  code?: string;
  message?: string;
  data?: PlaceVisitScrollResponse;
};

export type GetPlaceVisitsParams = {
  /**
   * 이전 응답의 nextCursorPurchaseDate (첫 조회 시 생략)
   */
  cursorPurchaseDate?: string;
  /**
   * 이전 응답의 nextCursorPurchaseTime (첫 조회 시 생략)
   */
  cursorPurchaseTime?: string;
  /**
   * 이전 응답의 nextCursorId (첫 조회 시 생략)
   */
  cursorId?: number;
  size?: number;
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
