/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useQuery, useSuspenseQuery } from '@tanstack/react-query';

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponse,
  GetPlaceVisitsParams,
  SearchVisitedPlacesParams,
  SecondParameter,
} from '@/features/shop/apis/dto';

import { getPlaceDetail, getPlaceVisits, searchVisitedPlaces } from '@/features/shop/apis/clients';

import {
  getGetPlaceDetailQueryKey,
  getGetPlaceVisitsQueryKey,
  getSearchVisitedPlacesQueryKey,
} from '@/features/shop/apis/queryKeys';

export const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getSearchVisitedPlacesQueryOptions = <
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchVisitedPlacesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVisitedPlaces>>> = ({ signal }) =>
    searchVisitedPlaces(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchVisitedPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchVisitedPlacesQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchVisitedPlaces>>
>;

export type SearchVisitedPlacesQueryError = ErrorType<ApiResponse>;

export function useSearchVisitedPlaces<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVisitedPlaces>>,
          TError,
          Awaited<ReturnType<typeof searchVisitedPlaces>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchVisitedPlaces<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVisitedPlaces>>,
          TError,
          Awaited<ReturnType<typeof searchVisitedPlaces>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchVisitedPlaces<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 방문 장소 검색
 */

export function useSearchVisitedPlaces<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchVisitedPlacesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getSearchVisitedPlacesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchVisitedPlacesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVisitedPlaces>>> = ({ signal }) =>
    searchVisitedPlaces(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof searchVisitedPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchVisitedPlacesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchVisitedPlaces>>
>;

export type SearchVisitedPlacesSuspenseQueryError = ErrorType<ApiResponse>;

export function useSearchVisitedPlacesSuspense<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchVisitedPlacesSuspense<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchVisitedPlacesSuspense<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 방문 장소 검색
 */

export function useSearchVisitedPlacesSuspense<
  TData = Awaited<ReturnType<typeof searchVisitedPlaces>>,
  TError = ErrorType<ApiResponse>,
>(
  params: SearchVisitedPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchVisitedPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchVisitedPlacesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetPlaceDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlaceDetailQueryKey(placeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlaceDetail>>> = ({ signal }) =>
    getPlaceDetail(placeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: placeId !== null && placeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPlaceDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaceDetail>>>;

export type GetPlaceDetailQueryError = ErrorType<unknown>;

export function useGetPlaceDetail<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlaceDetail>>,
          TError,
          Awaited<ReturnType<typeof getPlaceDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceDetail<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlaceDetail>>,
          TError,
          Awaited<ReturnType<typeof getPlaceDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceDetail<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 장소 상세 조회
 */

export function useGetPlaceDetail<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPlaceDetailQueryOptions(placeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetPlaceDetailSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlaceDetailQueryKey(placeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlaceDetail>>> = ({ signal }) =>
    getPlaceDetail(placeId, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPlaceDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPlaceDetailSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlaceDetail>>
>;

export type GetPlaceDetailSuspenseQueryError = ErrorType<unknown>;

export function useGetPlaceDetailSuspense<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceDetailSuspense<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceDetailSuspense<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 장소 상세 조회
 */

export function useGetPlaceDetailSuspense<
  TData = Awaited<ReturnType<typeof getPlaceDetail>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPlaceDetailSuspenseQueryOptions(placeId, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetPlaceVisitsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlaceVisitsQueryKey(placeId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlaceVisits>>> = ({ signal }) =>
    getPlaceVisits(placeId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: placeId !== null && placeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPlaceVisitsQueryResult = NonNullable<Awaited<ReturnType<typeof getPlaceVisits>>>;

export type GetPlaceVisitsQueryError = ErrorType<unknown>;

export function useGetPlaceVisits<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params: undefined | GetPlaceVisitsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlaceVisits>>,
          TError,
          Awaited<ReturnType<typeof getPlaceVisits>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceVisits<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlaceVisits>>,
          TError,
          Awaited<ReturnType<typeof getPlaceVisits>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceVisits<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 장소별 방문 이력 무한스크롤 조회
 */

export function useGetPlaceVisits<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPlaceVisitsQueryOptions(placeId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetPlaceVisitsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlaceVisitsQueryKey(placeId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlaceVisits>>> = ({ signal }) =>
    getPlaceVisits(placeId, params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getPlaceVisits>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPlaceVisitsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlaceVisits>>
>;

export type GetPlaceVisitsSuspenseQueryError = ErrorType<unknown>;

export function useGetPlaceVisitsSuspense<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params: undefined | GetPlaceVisitsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceVisitsSuspense<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPlaceVisitsSuspense<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 장소별 방문 이력 무한스크롤 조회
 */

export function useGetPlaceVisitsSuspense<
  TData = Awaited<ReturnType<typeof getPlaceVisits>>,
  TError = ErrorType<unknown>,
>(
  placeId: number,
  params?: GetPlaceVisitsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPlaceVisits>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPlaceVisitsSuspenseQueryOptions(placeId, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
