/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import type { GetPlaceVisitsParams } from '@/features/shop/apis/dto';

export const getGetPlaceDetailQueryKey = (placeId: number) => {
  return [`/consumptions/places/${placeId}`] as const;
};

export const getGetPlaceVisitsQueryKey = (placeId: number, params?: GetPlaceVisitsParams) => {
  return [`/consumptions/places/${placeId}/visits`, ...(params ? [params] : [])] as const;
};
