/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

/**
 * 내 정보 조회 결과
 */
export type AccountResponse = {
  /** 사용자 식별자 */
  userId?: number;
  /** 닉네임 */
  nickname?: string;
  /**
   * 프로필 이미지 URL
   * @nullable
   */
  profileImageUrl?: string | null;
};

export type ApiResponseAccountResponse = {
  code?: string;
  message?: string;
  data?: AccountResponse;
};

export type ApiResponse = {
  code?: string;
  message?: string;
  data?: unknown;
};

export type ApiResponseVoid = {
  code?: string;
  message?: string;
  data?: unknown;
};

/**
 * 내 정보 수정 요청
 */
export type AccountUpdateRequest = {
  /**
   * 변경할 닉네임
   * @minLength 2
   * @maxLength 10
   * @nullable
   * @pattern .*\S.*
   */
  nickname?: string | null;
  /**
   * 변경할 프로필 이미지 (JPEG, PNG, 최대 5MB, 최대 4096x4096)
   * @nullable
   */
  profileImage?: Blob | null;
  /** 기존 프로필 이미지 삭제 여부 */
  deleteProfileImage?: boolean;
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
