/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useMutation } from '@tanstack/react-query';

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType, BodyType } from '@/shared/apis/orvalMutator';

import type {
  AccountUpdateRequest,
  ApiResponse,
  SecondParameter,
} from '@/features/my-page/apis/dto';

import { updateMyAccount, withdrawMyAccount } from '@/features/my-page/apis/clients';

export const getWithdrawMyAccountMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof withdrawMyAccount>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof withdrawMyAccount>>, TError, void, TContext> => {
  const mutationKey = ['withdrawMyAccount'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof withdrawMyAccount>>, void> = () => {
    return withdrawMyAccount(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WithdrawMyAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof withdrawMyAccount>>
>;

export type WithdrawMyAccountMutationError = ErrorType<ApiResponse>;

/**
 * @summary 회원 탈퇴
 */
export const useWithdrawMyAccount = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof withdrawMyAccount>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof withdrawMyAccount>>, TError, void, TContext> => {
  return useMutation(getWithdrawMyAccountMutationOptions(options), queryClient);
};

export const getUpdateMyAccountMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyAccount>>,
    TError,
    { data?: BodyType<AccountUpdateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMyAccount>>,
  TError,
  { data?: BodyType<AccountUpdateRequest> },
  TContext
> => {
  const mutationKey = ['updateMyAccount'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMyAccount>>,
    { data?: BodyType<AccountUpdateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return updateMyAccount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMyAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMyAccount>>
>;

export type UpdateMyAccountMutationBody = BodyType<AccountUpdateRequest> | undefined;

export type UpdateMyAccountMutationError = ErrorType<ApiResponse>;

/**
 * @summary 내 정보 수정
 */
export const useUpdateMyAccount = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMyAccount>>,
      TError,
      { data?: BodyType<AccountUpdateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateMyAccount>>,
  TError,
  { data?: BodyType<AccountUpdateRequest> },
  TContext
> => {
  return useMutation(getUpdateMyAccountMutationOptions(options), queryClient);
};
