/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useQuery, useSuspenseQuery } from '@tanstack/react-query';

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType } from '@/shared/apis/orvalMutator';

import type { ApiResponse, SecondParameter } from '@/features/my-page/apis/dto';

import { getMyAccount } from '@/features/my-page/apis/clients';

import { getGetMyAccountQueryKey } from '@/features/my-page/apis/queryKeys';

export const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetMyAccountQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>>;
  request?: SecondParameter<typeof apiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyAccountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyAccount>>> = ({ signal }) =>
    getMyAccount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyAccount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyAccountQueryResult = NonNullable<Awaited<ReturnType<typeof getMyAccount>>>;

export type GetMyAccountQueryError = ErrorType<ApiResponse>;

export function useGetMyAccount<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyAccount>>,
          TError,
          Awaited<ReturnType<typeof getMyAccount>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyAccount<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyAccount>>,
          TError,
          Awaited<ReturnType<typeof getMyAccount>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyAccount<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 내 정보 조회
 */

export function useGetMyAccount<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyAccountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetMyAccountSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>>;
  request?: SecondParameter<typeof apiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyAccountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyAccount>>> = ({ signal }) =>
    getMyAccount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMyAccount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyAccountSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMyAccount>>>;

export type GetMyAccountSuspenseQueryError = ErrorType<ApiResponse>;

export function useGetMyAccountSuspense<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyAccountSuspense<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyAccountSuspense<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 내 정보 조회
 */

export function useGetMyAccountSuspense<
  TData = Awaited<ReturnType<typeof getMyAccount>>,
  TError = ErrorType<ApiResponse>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyAccount>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyAccountSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
