/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type { BodyType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponseAuthenticationResponse,
  ApiResponseVoid,
  CompleteSocialOAuthParams,
  LoginCodeExchangeRequest,
  RefreshTokenRequest,
  SecondParameter,
  StartParams,
  TermsAgreementRequest,
} from '@/features/auth/apis/dto';

/**
 * APP Refresh Token을 요청 본문으로 받아 기존 토큰을 폐기하고 새 토큰 쌍을 발급합니다.
 *
 * 발급된 Access Token과 Refresh Token은 모두 응답 본문으로 전달합니다.
 *
 * Authorization 헤더 없이 호출합니다.
 * @summary 앱 토큰 재발급
 */
export const refreshApp = (
  refreshTokenRequest: BodyType<RefreshTokenRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseAuthenticationResponse>(
    {
      url: `/auth/token/refresh`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: refreshTokenRequest,
      signal,
    },
    options
  );
};

/**
 * HttpOnly 쿠키의 WEB Refresh Token을 사용해 기존 토큰을 폐기하고 새 토큰을 발급합니다.
 *
 * Access Token은 응답 본문으로, 새 Refresh Token은 HttpOnly 쿠키로 전달합니다.
 *
 * 브라우저 요청에 credentials를 포함하고 Authorization 헤더 없이 호출합니다.
 * @summary 웹 토큰 재발급
 */
export const refreshWeb = (options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
  return apiClient<ApiResponseAuthenticationResponse>(
    { url: `/auth/token/refresh/web`, method: 'POST', signal },
    options
  );
};

/**
 * 소셜 로그인 콜백이 전달한 일회용 loginCode와 로그인 시작 시 생성한 codeVerifier를 교환합니다.
 *
 * 가입이 완료된 사용자는 Access Token을 발급하고, 약관 동의가 필요한 사용자는 Signup Token을 발급합니다.
 *
 * WEB의 Refresh Token은 HttpOnly 쿠키로, APP의 Refresh Token은 응답 본문으로 전달합니다.
 *
 * Authorization 헤더 없이 호출합니다.
 * @summary 소셜 로그인 코드 교환
 */
export const exchangeSocialLoginCode = (
  loginCodeExchangeRequest: BodyType<LoginCodeExchangeRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseAuthenticationResponse>(
    {
      url: `/auth/social/exchange`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginCodeExchangeRequest,
      signal,
    },
    options
  );
};

/**
 * 로그인 코드 교환에서 발급된 Signup Token을 Bearer 토큰으로 사용합니다.
 *
 * ageConfirmed와 serviceTermsAgreed가 모두 true이면 회원가입을 완료하고 Access Token과 Refresh Token을 발급합니다.
 *
 * Refresh Token 전달 방식은 로그인한 WEB/APP 유형을 따릅니다.
 * @summary 가입 자격 확인 및 서비스 이용약관 동의로 회원가입 완료
 */
export const agree = (
  termsAgreementRequest: BodyType<TermsAgreementRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseAuthenticationResponse>(
    {
      url: `/auth/signup/terms`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: termsAgreementRequest,
      signal,
    },
    options
  );
};

/**
 * APP Refresh Token을 요청 본문으로 받아 서버에 저장된 토큰을 폐기합니다.
 *
 * 앱은 응답을 받은 뒤 로컬에 저장한 Access Token과 Refresh Token을 삭제합니다.
 *
 * Authorization 헤더 없이 호출합니다.
 * @summary 앱 로그아웃
 */
export const logoutApp = (
  refreshTokenRequest: BodyType<RefreshTokenRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseVoid>(
    {
      url: `/auth/logout`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: refreshTokenRequest,
      signal,
    },
    options
  );
};

/**
 * HttpOnly 쿠키의 WEB Refresh Token을 서버에서 폐기하고 쿠키를 만료시킵니다.
 *
 * 브라우저 요청에 credentials를 포함하고 Authorization 헤더 없이 호출합니다.
 * @summary 웹 로그아웃
 */
export const logoutWeb = (options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
  return apiClient<ApiResponseVoid>({ url: `/auth/logout/web`, method: 'POST', signal }, options);
};

/**
 * 소셜 로그인 제공자, 클라이언트 유형과 PKCE codeChallenge를 저장한 뒤
 *
 * 브라우저를 해당 제공자의 인증 화면으로 이동시킵니다.
 * @summary 소셜 로그인 시작
 */
export const start = (
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<unknown>(
    { url: `/oauth/${provider}/start`, method: 'GET', params, signal },
    options
  );
};

/**
 * 소셜 로그인 제공자가 호출하는 콜백입니다. 인증 결과를 처리한 뒤 WEB 또는 APP 리디렉션 URI로
 *
 * 일회용 loginCode를 전달합니다. 취소하거나 처리에 실패하면 error를 전달합니다.
 * @summary 소셜 로그인 콜백
 */
export const completeSocialOAuth = (
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<unknown>(
    { url: `/oauth/${provider}/callback`, method: 'GET', params, signal },
    options
  );
};
