/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

/**
 * APP Refresh Token 요청
 */
export type RefreshTokenRequest = {
  /**
   * APP 로그인 또는 이전 재발급에서 받은 Refresh Token
   * @minLength 1
   */
  refreshToken: string;
};

/**
 * 인증 처리 결과입니다.
 *
 * - 약관 동의 필요: requiresTermsAgreement=true이며 signupToken을 발급합니다.
 * - WEB 인증 완료: accessToken을 발급하고 Refresh Token은 HttpOnly 쿠키로 전달합니다.
 * - APP 인증 완료: accessToken과 refreshToken을 발급합니다.
 */
export type AuthenticationResponse = {
  /** 필수 약관 동의 필요 여부 */
  requiresTermsAgreement?: boolean;
  /**
   * 약관 동의가 필요할 때만 발급되는 15분 유효 Signup Token
   * @nullable
   */
  signupToken?: string | null;
  /**
   * 인증이 완료된 사용자에게 발급되는 30분 유효 Access Token
   * @nullable
   */
  accessToken?: string | null;
  /**
   * APP 인증 완료 시에만 응답 본문에 포함되는 14일 유효 Refresh Token
   * @nullable
   */
  refreshToken?: string | null;
};

export type ApiResponseAuthenticationResponse = {
  code?: string;
  message?: string;
  data?: AuthenticationResponse;
};

export type ApiResponse = {
  code?: string;
  message?: string;
  data?: unknown;
};

/**
 * 소셜 로그인 코드 교환 요청
 */
export type LoginCodeExchangeRequest = {
  /**
   * 소셜 로그인 콜백 이후 클라이언트 리디렉션 URI로 전달된 일회용 로그인 코드
   * @minLength 1
   */
  loginCode: string;
  /**
   * 로그인 시작 시 codeChallenge 생성에 사용한 PKCE codeVerifier
   * @minLength 1
   * @pattern [A-Za-z0-9._~-]{43,128}
   */
  codeVerifier: string;
};

/**
 * 서비스 이용약관 동의 요청
 */
export type TermsAgreementRequest = {
  /** 서비스 이용약관 동의 여부 */
  serviceTermsAgreed: boolean;
};

export type ApiResponseVoid = {
  code?: string;
  message?: string;
  data?: unknown;
};

export type StartParams = {
  /**
   * 로그인을 시작한 클라이언트 유형 (WEB_LOCAL은 localhost 테스트용)
   */
  client: StartClient;
  /**
   * PKCE S256 방식으로 생성한 43자 codeChallenge
   */
  codeChallenge: string;
};

export type StartClient = (typeof StartClient)[keyof typeof StartClient];

export const StartClient = {
  WEB: 'WEB',
  WEB_LOCAL: 'WEB_LOCAL',
  APP: 'APP',
} as const;

export type CompleteSocialOAuthParams = {
  /**
   * 소셜 로그인 제공자가 발급한 Authorization Code
   */
  code?: string;
  /**
   * 로그인 시작 시 서버가 발급한 일회용 OAuth state
   */
  state: string;
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
