/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useMutation } from '@tanstack/react-query';

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType, BodyType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponse,
  LoginCodeExchangeRequest,
  RefreshTokenRequest,
  SecondParameter,
  TermsAgreementRequest,
} from '@/features/auth/apis/dto';

import {
  agree,
  exchangeSocialLoginCode,
  logoutApp,
  logoutWeb,
  refreshApp,
  refreshWeb,
} from '@/features/auth/apis/clients';

export const getRefreshAppMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshApp>>,
    TError,
    { data: BodyType<RefreshTokenRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshApp>>,
  TError,
  { data: BodyType<RefreshTokenRequest> },
  TContext
> => {
  const mutationKey = ['refreshApp'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshApp>>,
    { data: BodyType<RefreshTokenRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return refreshApp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshAppMutationResult = NonNullable<Awaited<ReturnType<typeof refreshApp>>>;

export type RefreshAppMutationBody = BodyType<RefreshTokenRequest>;

export type RefreshAppMutationError = ErrorType<ApiResponse>;

/**
 * @summary 앱 토큰 재발급
 */
export const useRefreshApp = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshApp>>,
      TError,
      { data: BodyType<RefreshTokenRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof refreshApp>>,
  TError,
  { data: BodyType<RefreshTokenRequest> },
  TContext
> => {
  return useMutation(getRefreshAppMutationOptions(options), queryClient);
};

export const getRefreshWebMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof refreshWeb>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof refreshWeb>>, TError, void, TContext> => {
  const mutationKey = ['refreshWeb'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshWeb>>, void> = () => {
    return refreshWeb(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshWebMutationResult = NonNullable<Awaited<ReturnType<typeof refreshWeb>>>;

export type RefreshWebMutationError = ErrorType<ApiResponse>;

/**
 * @summary 웹 토큰 재발급
 */
export const useRefreshWeb = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof refreshWeb>>, TError, void, TContext>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof refreshWeb>>, TError, void, TContext> => {
  return useMutation(getRefreshWebMutationOptions(options), queryClient);
};

export const getExchangeSocialLoginCodeMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exchangeSocialLoginCode>>,
    TError,
    { data: BodyType<LoginCodeExchangeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof exchangeSocialLoginCode>>,
  TError,
  { data: BodyType<LoginCodeExchangeRequest> },
  TContext
> => {
  const mutationKey = ['exchangeSocialLoginCode'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof exchangeSocialLoginCode>>,
    { data: BodyType<LoginCodeExchangeRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return exchangeSocialLoginCode(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExchangeSocialLoginCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof exchangeSocialLoginCode>>
>;

export type ExchangeSocialLoginCodeMutationBody = BodyType<LoginCodeExchangeRequest>;

export type ExchangeSocialLoginCodeMutationError = ErrorType<ApiResponse>;

/**
 * @summary 소셜 로그인 코드 교환
 */
export const useExchangeSocialLoginCode = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof exchangeSocialLoginCode>>,
      TError,
      { data: BodyType<LoginCodeExchangeRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof exchangeSocialLoginCode>>,
  TError,
  { data: BodyType<LoginCodeExchangeRequest> },
  TContext
> => {
  return useMutation(getExchangeSocialLoginCodeMutationOptions(options), queryClient);
};

export const getAgreeMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof agree>>,
    TError,
    { data: BodyType<TermsAgreementRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof agree>>,
  TError,
  { data: BodyType<TermsAgreementRequest> },
  TContext
> => {
  const mutationKey = ['agree'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof agree>>,
    { data: BodyType<TermsAgreementRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return agree(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AgreeMutationResult = NonNullable<Awaited<ReturnType<typeof agree>>>;

export type AgreeMutationBody = BodyType<TermsAgreementRequest>;

export type AgreeMutationError = ErrorType<ApiResponse>;

/**
 * @summary 필수 약관 동의 및 회원가입 완료
 */
export const useAgree = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof agree>>,
      TError,
      { data: BodyType<TermsAgreementRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof agree>>,
  TError,
  { data: BodyType<TermsAgreementRequest> },
  TContext
> => {
  return useMutation(getAgreeMutationOptions(options), queryClient);
};

export const getLogoutAppMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutApp>>,
    TError,
    { data: BodyType<RefreshTokenRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutApp>>,
  TError,
  { data: BodyType<RefreshTokenRequest> },
  TContext
> => {
  const mutationKey = ['logoutApp'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutApp>>,
    { data: BodyType<RefreshTokenRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return logoutApp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutAppMutationResult = NonNullable<Awaited<ReturnType<typeof logoutApp>>>;

export type LogoutAppMutationBody = BodyType<RefreshTokenRequest>;

export type LogoutAppMutationError = ErrorType<ApiResponse>;

/**
 * @summary 앱 로그아웃
 */
export const useLogoutApp = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logoutApp>>,
      TError,
      { data: BodyType<RefreshTokenRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof logoutApp>>,
  TError,
  { data: BodyType<RefreshTokenRequest> },
  TContext
> => {
  return useMutation(getLogoutAppMutationOptions(options), queryClient);
};

export const getLogoutWebMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof logoutWeb>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof logoutWeb>>, TError, void, TContext> => {
  const mutationKey = ['logoutWeb'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutWeb>>, void> = () => {
    return logoutWeb(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutWebMutationResult = NonNullable<Awaited<ReturnType<typeof logoutWeb>>>;

export type LogoutWebMutationError = ErrorType<ApiResponse>;

/**
 * @summary 웹 로그아웃
 */
export const useLogoutWeb = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof logoutWeb>>, TError, void, TContext>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof logoutWeb>>, TError, void, TContext> => {
  return useMutation(getLogoutWebMutationOptions(options), queryClient);
};
