/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

/**
 * 소비 기록 등록 요청
 */
export type ConsumptionCreateRequest = {
  /**
   * OCR에서 발급받은 임시 영수증 이미지 ID
   * @nullable
   */
  receiptImageId?: number | null;
  /**
   * Google Place ID
   * @minLength 0
   * @maxLength 255
   */
  googlePlaceId: string;
  /**
   * 장소명
   * @minLength 0
   * @maxLength 100
   */
  placeName: string;
  /**
   * 사용자가 확인한 도로명주소
   * @minLength 0
   * @maxLength 255
   */
  roadAddress: string;
  /**
   * Google Places에서 받은 위도
   * @minimum -90
   * @maximum 90
   */
  latitude: number;
  /**
   * Google Places에서 받은 경도
   * @minimum -180
   * @maximum 180
   */
  longitude: number;
  /** 소비 날짜 */
  purchaseDate: string;
  /** 소비 시간 */
  purchaseTime: string;
  /** 소비 금액(원) */
  amount: number;
  /**
   * 소비 카테고리
   * @minLength 0
   * @maxLength 40
   * @pattern ^(카페|운동|편의점/마트|취미/놀거리|음식점|미용/뷰티|기타)$
   */
  category: string;
};

/**
 * 소비 기록 등록 결과
 */
export type ConsumptionCreateResponse = {
  /** 생성된 소비 기록 ID */
  consumptionId?: number;
  /** 획득한 스티커 카테고리 */
  stickerCategory?: string;
  /** 획득한 스티커 이름 */
  stickerName?: string;
};

export type ApiResponseConsumptionCreateResponse = {
  code?: string;
  message?: string;
  data?: ConsumptionCreateResponse;
};

export type ApiResponse = {
  code?: string;
  message?: string;
  data?: unknown;
};

/**
 * 영수증 OCR 요청
 */
export type ReceiptOcrRequest = {
  /** OCR 처리할 영수증 이미지 (JPEG, PNG, 최대 5MB, 최대 4096x4096) */
  receiptImage: Blob;
};

/**
 * Google Place 검색 결과
 */
export type GooglePlaceSearchResultResponse = {
  /** Google Place ID */
  googlePlaceId?: string;
  /** 장소명 */
  placeName?: string;
  /** 도로명주소 */
  roadAddress?: string;
  /** 위도 */
  latitude?: number;
  /** 경도 */
  longitude?: number;
  /**
   * 장소 썸네일 URL
   * @nullable
   */
  thumbnailUrl?: string | null;
};

/**
 * 영수증 OCR 인식 결과
 */
export type ReceiptOcrResponse = {
  /** 임시 저장된 영수증 이미지 ID */
  receiptImageId?: number;
  /**
   * 인식된 상호명
   * @nullable
   */
  storeName?: string | null;
  /**
   * 인식된 주소
   * @nullable
   */
  address?: string | null;
  /**
   * 인식된 구매 날짜
   * @nullable
   */
  purchaseDate?: string | null;
  /**
   * 인식된 구매 시간
   * @nullable
   */
  purchaseTime?: string | null;
  /**
   * 인식된 결제 금액(원)
   * @nullable
   */
  amount?: number | null;
  /** OCR 결과로 조회한 Google Place 검색 결과 */
  googlePlaceSearchResult?: GooglePlaceSearchResultResponse | null;
};

export type ApiResponseReceiptOcrResponse = {
  code?: string;
  message?: string;
  data?: ReceiptOcrResponse;
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
