/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useMutation } from '@tanstack/react-query';

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType, BodyType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponse,
  ConsumptionCreateRequest,
  ReceiptOcrRequest,
  SecondParameter,
} from '@/features/record/apis/dto';

import { createConsumption, recognizeReceipt } from '@/features/record/apis/clients';

export const getCreateConsumptionMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createConsumption>>,
    TError,
    { data: BodyType<ConsumptionCreateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createConsumption>>,
  TError,
  { data: BodyType<ConsumptionCreateRequest> },
  TContext
> => {
  const mutationKey = ['createConsumption'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createConsumption>>,
    { data: BodyType<ConsumptionCreateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createConsumption(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateConsumptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createConsumption>>
>;

export type CreateConsumptionMutationBody = BodyType<ConsumptionCreateRequest>;

export type CreateConsumptionMutationError = ErrorType<ApiResponse>;

/**
 * @summary 소비 기록 등록
 */
export const useCreateConsumption = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createConsumption>>,
      TError,
      { data: BodyType<ConsumptionCreateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createConsumption>>,
  TError,
  { data: BodyType<ConsumptionCreateRequest> },
  TContext
> => {
  return useMutation(getCreateConsumptionMutationOptions(options), queryClient);
};

export const getRecognizeReceiptMutationOptions = <
  TError = ErrorType<ApiResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recognizeReceipt>>,
    TError,
    { data?: BodyType<ReceiptOcrRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recognizeReceipt>>,
  TError,
  { data?: BodyType<ReceiptOcrRequest> },
  TContext
> => {
  const mutationKey = ['recognizeReceipt'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recognizeReceipt>>,
    { data?: BodyType<ReceiptOcrRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return recognizeReceipt(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecognizeReceiptMutationResult = NonNullable<
  Awaited<ReturnType<typeof recognizeReceipt>>
>;

export type RecognizeReceiptMutationBody = BodyType<ReceiptOcrRequest> | undefined;

export type RecognizeReceiptMutationError = ErrorType<ApiResponse>;

/**
 * @summary 영수증 OCR 요청
 */
export const useRecognizeReceipt = <TError = ErrorType<ApiResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recognizeReceipt>>,
      TError,
      { data?: BodyType<ReceiptOcrRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof recognizeReceipt>>,
  TError,
  { data?: BodyType<ReceiptOcrRequest> },
  TContext
> => {
  return useMutation(getRecognizeReceiptMutationOptions(options), queryClient);
};
