/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useQuery, useSuspenseQuery } from '@tanstack/react-query';

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponse,
  CompleteSocialOAuthParams,
  SecondParameter,
  StartParams,
} from '@/features/auth/api/dto';

import { completeSocialOAuth, start } from '@/features/auth/api/clients';

export const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getStartQueryKey = (provider: 'kakao' | 'google', params?: StartParams) => {
  return [`/oauth/${provider}/start`, ...(params ? [params] : [])] as const;
};

export const getStartQueryOptions = <
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStartQueryKey(provider, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof start>>> = ({ signal }) =>
    start(provider, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: provider !== null && provider !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type StartQueryResult = NonNullable<Awaited<ReturnType<typeof start>>>;

export type StartQueryError = ErrorType<void | ApiResponse>;

export function useStart<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof start>>,
          TError,
          Awaited<ReturnType<typeof start>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useStart<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof start>>,
          TError,
          Awaited<ReturnType<typeof start>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useStart<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 소셜 로그인 시작
 */

export function useStart<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStartQueryOptions(provider, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getStartSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStartQueryKey(provider, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof start>>> = ({ signal }) =>
    start(provider, params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof start>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StartSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof start>>>;

export type StartSuspenseQueryError = ErrorType<void | ApiResponse>;

export function useStartSuspense<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useStartSuspense<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useStartSuspense<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 소셜 로그인 시작
 */

export function useStartSuspense<
  TData = Awaited<ReturnType<typeof start>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: 'kakao' | 'google',
  params: StartParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof start>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStartSuspenseQueryOptions(provider, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCompleteSocialOAuthQueryKey = (
  provider: string,
  params?: CompleteSocialOAuthParams
) => {
  return [`/oauth/${provider}/callback`, ...(params ? [params] : [])] as const;
};

export const getCompleteSocialOAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompleteSocialOAuthQueryKey(provider, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof completeSocialOAuth>>> = ({ signal }) =>
    completeSocialOAuth(provider, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: provider !== null && provider !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type CompleteSocialOAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof completeSocialOAuth>>
>;

export type CompleteSocialOAuthQueryError = ErrorType<void | ApiResponse>;

export function useCompleteSocialOAuth<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof completeSocialOAuth>>,
          TError,
          Awaited<ReturnType<typeof completeSocialOAuth>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useCompleteSocialOAuth<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof completeSocialOAuth>>,
          TError,
          Awaited<ReturnType<typeof completeSocialOAuth>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useCompleteSocialOAuth<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 소셜 로그인 콜백
 */

export function useCompleteSocialOAuth<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCompleteSocialOAuthQueryOptions(provider, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCompleteSocialOAuthSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompleteSocialOAuthQueryKey(provider, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof completeSocialOAuth>>> = ({ signal }) =>
    completeSocialOAuth(provider, params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof completeSocialOAuth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompleteSocialOAuthSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof completeSocialOAuth>>
>;

export type CompleteSocialOAuthSuspenseQueryError = ErrorType<void | ApiResponse>;

export function useCompleteSocialOAuthSuspense<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useCompleteSocialOAuthSuspense<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useCompleteSocialOAuthSuspense<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 소셜 로그인 콜백
 */

export function useCompleteSocialOAuthSuspense<
  TData = Awaited<ReturnType<typeof completeSocialOAuth>>,
  TError = ErrorType<void | ApiResponse>,
>(
  provider: string,
  params: CompleteSocialOAuthParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof completeSocialOAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCompleteSocialOAuthSuspenseQueryOptions(provider, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
