name: ♻️ Refactor
description: 리팩토링 이슈를 생성합니다. 코드 리팩토링 이슈 템플릿입니다.
title: '[♻️ Refactor] '
labels:
  - '♻️ Refactor'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 작업 종류 (Feature Type)'
      description: 작업 종류의 Jira Ticket Number를 기입해주세요
      value: KAN-3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📌 설명'
      description: 리팩토링할 부분과 목적을 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '🛠️ 구현 목록'
      description: 구체적으로 작성하기
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
