/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type { BodyType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponseBoolean,
  ApiResponseListNotificationResponse,
  ApiResponseVoid,
  DeviceTokenRegisterRequest,
  GetNotificationsParams,
  SecondParameter,
} from '@/features/notification/apis/dto';

export const unregisterDeviceToken = (
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseVoid>(
    { url: `/accounts/me/device-token`, method: 'DELETE', signal },
    options
  );
};

/**
 * @summary 디바이스 토큰 등록
 */
export const registerDeviceToken = (
  deviceTokenRegisterRequest: BodyType<DeviceTokenRegisterRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseVoid>(
    {
      url: `/accounts/me/device-token`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: deviceTokenRegisterRequest,
      signal,
    },
    options
  );
};

/**
 * 호출 시 모든 알림 조회처리
 * @summary 알림 목록 조회
 */
export const getNotifications = (
  params?: GetNotificationsParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseListNotificationResponse>(
    { url: `/notifications`, method: 'GET', params, signal },
    options
  );
};

/**
 * 홈화면에서 알림 존재 유무를 확인합니다.
 * @summary 읽지 않은 알림 확인 조회
 */
export const hasUnread = (options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
  return apiClient<ApiResponseBoolean>(
    { url: `/notifications/unread-exists`, method: 'GET', signal },
    options
  );
};
