/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

export type ApiResponseVoid = {
  code?: string;
  message?: string;
  data?: unknown;
};

export type DeviceTokenRegisterRequest = {
  /** @minLength 1 */
  fcmToken: string;
};

export type NotificationResponseType =
  (typeof NotificationResponseType)[keyof typeof NotificationResponseType];

export const NotificationResponseType = {
  REPORT_COMPLETED: 'REPORT_COMPLETED',
  FRIDAY_REMINDER: 'FRIDAY_REMINDER',
} as const;

export type NotificationResponse = {
  id?: number;
  type?: NotificationResponseType;
  title?: string;
  body?: string;
  read?: boolean;
  createdAt?: string;
};

export type ApiResponseListNotificationResponse = {
  code?: string;
  message?: string;
  data?: NotificationResponse[];
};

export type ApiResponseBoolean = {
  code?: string;
  message?: string;
  data?: boolean;
};

export type GetNotificationsParams = {
  cursorId?: number;
  size?: number;
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
