/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

export type ApiResponseVoid = {
  code?: string;
  message?: string;
  data?: unknown;
};

export type DeviceTokenRegisterRequest = {
  /** @minLength 1 */
  pushToken: string;
};

export type NotificationResponse = {
  id?: number;
  type?: string;
  title?: string;
  body?: string;
  read?: boolean;
  createdAt?: string;
};

export type ApiResponseListNotificationResponse = {
  code?: string;
  message?: string;
  data?: NotificationResponse[];
};

export type ApiResponseBoolean = {
  code?: string;
  message?: string;
  data?: boolean;
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
