/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useMutation } from '@tanstack/react-query';

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType, BodyType } from '@/shared/apis/orvalMutator';

import type { DeviceTokenRegisterRequest, SecondParameter } from '@/features/notification/apis/dto';

import { registerDeviceToken, unregisterDeviceToken } from '@/features/notification/apis/clients';

export const getUnregisterDeviceTokenMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unregisterDeviceToken>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unregisterDeviceToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['unregisterDeviceToken'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unregisterDeviceToken>>,
    void
  > = () => {
    return unregisterDeviceToken(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnregisterDeviceTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof unregisterDeviceToken>>
>;

export type UnregisterDeviceTokenMutationError = ErrorType<unknown>;

export const useUnregisterDeviceToken = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unregisterDeviceToken>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof unregisterDeviceToken>>, TError, void, TContext> => {
  return useMutation(getUnregisterDeviceTokenMutationOptions(options), queryClient);
};

export const getRegisterDeviceTokenMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerDeviceToken>>,
    TError,
    { data: BodyType<DeviceTokenRegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerDeviceToken>>,
  TError,
  { data: BodyType<DeviceTokenRegisterRequest> },
  TContext
> => {
  const mutationKey = ['registerDeviceToken'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerDeviceToken>>,
    { data: BodyType<DeviceTokenRegisterRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return registerDeviceToken(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterDeviceTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerDeviceToken>>
>;

export type RegisterDeviceTokenMutationBody = BodyType<DeviceTokenRegisterRequest>;

export type RegisterDeviceTokenMutationError = ErrorType<unknown>;

/**
 * @summary 디바이스 토큰 등록
 */
export const useRegisterDeviceToken = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerDeviceToken>>,
      TError,
      { data: BodyType<DeviceTokenRegisterRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof registerDeviceToken>>,
  TError,
  { data: BodyType<DeviceTokenRegisterRequest> },
  TContext
> => {
  return useMutation(getRegisterDeviceTokenMutationOptions(options), queryClient);
};
