/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import type { GetNotificationsParams } from '@/features/notification/apis/dto';

export const getGetNotificationsQueryKey = (params?: GetNotificationsParams) => {
  return [`/notifications`, ...(params ? [params] : [])] as const;
};

export const getHasUnreadQueryKey = () => {
  return [`/notifications/unread-exists`] as const;
};
