/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

export const getGetNotificationsQueryKey = () => {
  return [`/notifications`] as const;
};

export const getHasUnreadQueryKey = () => {
  return [`/notifications/unread-exists`] as const;
};
