/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type {
  ApiResponseConsumptionScrollResponse,
  ApiResponseCurrentStatusResponse,
  ApiResponseFrequentPlaceResponse,
  ApiResponseMonthlyReportResponse,
  ApiResponsePersonaCardResponse,
  ApiResponseShareLinkResponse,
  GetConsumptionsParams,
  GetCurrentStatusParams,
  GetFrequentPlacesParams,
  GetMonthlyReportParams,
  IssueShareLinkParams,
  SecondParameter,
} from '@/features/report/apis/dto';

/**
 * 연월(yyyy-MM) 기준 본인 리포트의 취향카드 공유 토큰을 발급한다. 이미 발급된 적이 있으면 기존 토큰을 그대로 반환한다.
 * @summary 취향카드 공유 링크 발급
 */
export const issueShareLink = (
  params: IssueShareLinkParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseShareLinkResponse>(
    { url: `/reports/monthly/share`, method: 'POST', params, signal },
    options
  );
};

/**
 * 계정과 연월(yyyy-MM) 기준으로 소비내역을 최신순 커서 기반으로 조회합니다. nextCursorPurchaseDate/nextCursorPurchaseTime/nextCursorId를 다음 요청에 넣어 보내면 됩니다.
 * @summary 월별 소비내역 무한스크롤 조회
 */
export const getConsumptions = (
  params: GetConsumptionsParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseConsumptionScrollResponse>(
    { url: `/consumptions`, method: 'GET', params, signal },
    options
  );
};

/**
 * 공유 토큰으로 페르소나 정보만 담긴 취향카드를 조회한다. 로그인 없이 접근 가능.
 * @summary 공유받은 취향카드 조회
 */
export const getSharedPersonaCard = (
  shareToken: string,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponsePersonaCardResponse>(
    { url: `/reports/share/${shareToken}`, method: 'GET', signal },
    options
  );
};

/**
 * 연월(yyyy-MM) 기준으로 집계된 월간 리포트를 조회한다.
 * @summary 월간 리포트 조회
 */
export const getMonthlyReport = (
  params: GetMonthlyReportParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseMonthlyReportResponse>(
    { url: `/reports/monthly`, method: 'GET', params, signal },
    options
  );
};

/**
 * 연월(yyyy-MM) 기준 이번 달 누적 소비건수와,주별 소비건수 및 멘트 노출
 * @summary 현재 리포트 현황 조회
 */
export const getCurrentStatus = (
  params: GetCurrentStatusParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseCurrentStatusResponse>(
    { url: `/reports/current`, method: 'GET', params, signal },
    options
  );
};

/**
 * 방문 횟수 내림차순으로 장소 랭킹을 커서 기반으로 조회합니다. period [이번달/전체누적]  category로 필터링 가능 (생략시 전체 카테고리). nextCursorVisitCount/nextCursorPlaceId/nextCursorRank를 다음 요청에 그대로 넣어 보내면 됩니다.
 * @summary 자주 소비한 곳 랭킹 무한스크롤 조회
 */
export const getFrequentPlaces = (
  params?: GetFrequentPlacesParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseFrequentPlaceResponse>(
    { url: `/consumptions/places/rank`, method: 'GET', params, signal },
    options
  );
};
