/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

export type ShareLinkResponse = {
  shareToken?: string;
};

export type ApiResponseShareLinkResponse = {
  code?: string;
  message?: string;
  data?: ShareLinkResponse;
};

export type MonthlyReportAggregationResultInfo = {
  yearMonth?: string;
  lockAcquired?: boolean;
  targetUserCount?: number;
  succeededCount?: number;
  failedUserIds?: number[];
};

export type ApiResponseMonthlyReportAggregationResultInfo = {
  code?: string;
  message?: string;
  data?: MonthlyReportAggregationResultInfo;
};

export type ConsumptionResponse = {
  id?: number;
  placeId?: number;
  placeName?: string;
  category?: string;
  amount?: number;
  purchaseDate?: string;
  purchaseTime?: string;
  thumbnailUrl?: string;
};

export type ConsumptionScrollResponse = {
  consumptions?: ConsumptionResponse[];
  hasNext?: boolean;
  nextCursorPurchaseDate?: string;
  nextCursorPurchaseTime?: string;
  nextCursorId?: number;
};

export type ApiResponseConsumptionScrollResponse = {
  code?: string;
  message?: string;
  data?: ConsumptionScrollResponse;
};

export type ScoresResponse = {
  scoreExploration?: number;
  scoreTownExpansion?: number;
  scoreDaytime?: number;
  scoreImpulsive?: number;
};

export type PersonaCardResponse = {
  nickname?: string;
  type?: string;
  typeName?: string;
  description?: string;
  keywords?: string[];
  scores?: ScoresResponse;
};

export type ApiResponsePersonaCardResponse = {
  code?: string;
  message?: string;
  data?: PersonaCardResponse;
};

export type PersonaResponse = {
  type?: string;
  typeName?: string;
  description?: string;
  keywords?: string[];
  scores?: ScoresResponse;
};

export type PlaceRankResponse = {
  rank?: number;
  placeId?: number;
  placeName?: string;
  visitCount?: number;
  firstVisitedDate?: string;
  category?: string;
  stickerNames?: string[];
};

export type TownRankResponse = {
  rank?: number;
  townName?: string;
  visitCount?: number;
};

export type SummaryResponse = {
  totalVisitCount?: number;
  newTownCount?: number;
  newPlaceCount?: number;
};

export type CategoryStatResponse = {
  category?: string;
  percentage?: number;
};

export type DayOfWeekCountResponse = {
  dayOfWeek?: number;
  visitCount?: number;
};

export type TimePatternResponse = {
  peakDayOfWeek?: string;
  peakTimeSlot?: string;
  dayOfWeekPattern?: DayOfWeekCountResponse[];
};

export type AdjacentPersonaResponse = {
  yearMonth?: string;
  type?: string;
};

export type MonthlyReportResponse = {
  reportId?: number;
  yearMonth?: string;
  persona?: PersonaResponse;
  placeRanks?: PlaceRankResponse[];
  townRanks?: TownRankResponse[];
  summary?: SummaryResponse;
  categoryStats?: CategoryStatResponse[];
  timePattern?: TimePatternResponse;
  firstAvailableYearMonth?: string;
  previous?: AdjacentPersonaResponse;
  next?: AdjacentPersonaResponse;
};

export type ApiResponseMonthlyReportResponse = {
  code?: string;
  message?: string;
  data?: MonthlyReportResponse;
};

export type StickerResponse = {
  itemName?: string;
  acquiredDate?: string;
};

export type CurrentStatusResponseMonthlyCategoryCounts = { [key: string]: number };

export type CurrentStatusResponse = {
  date?: string;
  weeklyCounts?: number[];
  monthlyCount?: number;
  monthlyCategoryCounts?: CurrentStatusResponseMonthlyCategoryCounts;
  recentDiscoveryMessage?: string;
  monthlyStickers?: StickerResponse[];
  firstAvailableYearMonth?: string;
};

export type ApiResponseCurrentStatusResponse = {
  code?: string;
  message?: string;
  data?: CurrentStatusResponse;
};

export type FrequentPlaceItem = {
  rank?: number;
  placeId?: number;
  placeName?: string;
  category?: string;
  dongname?: string;
  visitCount?: number;
  thumbnailUrl?: string;
};

export type FrequentPlaceResponse = {
  places?: FrequentPlaceItem[];
  hasNext?: boolean;
  nextCursorVisitCount?: number;
  nextCursorPlaceId?: number;
  nextCursorRank?: number;
};

export type ApiResponseFrequentPlaceResponse = {
  code?: string;
  message?: string;
  data?: FrequentPlaceResponse;
};

export type IssueShareLinkParams = {
  /**
   * 조회할 연월, 예: 2026-07
   */
  yearMonth: string;
};

export type AggregateMonthlyReportParams = {
  /**
   * 집계할 연월, 예: 2026-06
   */
  yearMonth: string;
};

export type GetConsumptionsParams = {
  /**
   * 조회할 연월, 예: 2026-07
   */
  yearMonth: string;
  /**
   * 이전 응답의 nextCursorPurchaseDate (첫 조회 시 생략)
   */
  cursorPurchaseDate?: string;
  /**
   * 이전 응답의 nextCursorPurchaseTime (첫 조회 시 생략)
   */
  cursorPurchaseTime?: string;
  /**
   * 이전 응답의 nextCursorId (첫 조회 시 생략)
   */
  cursorId?: number;
  size?: number;
};

export type GetMonthlyReportParams = {
  /**
   * 조회할 연월, 예: 2026-07
   */
  yearMonth: string;
};

export type GetCurrentStatusParams = {
  /**
   * 조회할 연월, 예: 2026-08
   */
  yearMonth: string;
};

export type GetFrequentPlacesParams = {
  /**
   * 조회 기간, 기본값 THIS_MONTH
   */
  period?: GetFrequentPlacesPeriod;
  /**
   * 필터링할 카테고리 (생략시 전체 카테고리)
   */
  category?: string[];
  /**
   * 이전 응답의 nextCursorVisitCount (첫 조회 시 생략)
   */
  cursorVisitCount?: number;
  /**
   * 이전 응답의 nextCursorPlaceId (첫 조회 시 생략)
   */
  cursorPlaceId?: number;
  /**
   * 이전 응답의 nextCursorRank (첫 조회 시 생략)
   */
  cursorRank?: number;
  size?: number;
};

export type GetFrequentPlacesPeriod =
  (typeof GetFrequentPlacesPeriod)[keyof typeof GetFrequentPlacesPeriod];

export const GetFrequentPlacesPeriod = {
  THIS_MONTH: 'THIS_MONTH',
  ALL_TIME: 'ALL_TIME',
} as const;

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
