/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useMutation } from '@tanstack/react-query';

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType } from '@/shared/apis/orvalMutator';

import type { IssueShareLinkParams, SecondParameter } from '@/features/report/apis/dto';

import { issueShareLink } from '@/features/report/apis/clients';

export const getIssueShareLinkMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof issueShareLink>>,
    TError,
    { params: IssueShareLinkParams },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof issueShareLink>>,
  TError,
  { params: IssueShareLinkParams },
  TContext
> => {
  const mutationKey = ['issueShareLink'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof issueShareLink>>,
    { params: IssueShareLinkParams }
  > = (props) => {
    const { params } = props ?? {};

    return issueShareLink(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IssueShareLinkMutationResult = NonNullable<Awaited<ReturnType<typeof issueShareLink>>>;

export type IssueShareLinkMutationError = ErrorType<unknown>;

/**
 * @summary 취향카드 공유 링크 발급
 */
export const useIssueShareLink = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof issueShareLink>>,
      TError,
      { params: IssueShareLinkParams },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof issueShareLink>>,
  TError,
  { params: IssueShareLinkParams },
  TContext
> => {
  return useMutation(getIssueShareLinkMutationOptions(options), queryClient);
};
