/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { useQuery, useSuspenseQuery } from '@tanstack/react-query';

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import { apiClient } from '@/shared/apis/orvalMutator';

import type { ErrorType } from '@/shared/apis/orvalMutator';

import type {
  GetConsumptionsParams,
  GetCurrentStatusParams,
  GetFrequentPlacesParams,
  GetMonthlyReportParams,
  SecondParameter,
} from '@/features/report/apis/dto';

import {
  getConsumptions,
  getCurrentStatus,
  getFrequentPlaces,
  getMonthlyReport,
  getSharedPersonaCard,
} from '@/features/report/apis/clients';

import {
  getGetConsumptionsQueryKey,
  getGetCurrentStatusQueryKey,
  getGetFrequentPlacesQueryKey,
  getGetMonthlyReportQueryKey,
  getGetSharedPersonaCardQueryKey,
} from '@/features/report/apis/queryKeys';

export const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetConsumptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetConsumptionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConsumptions>>> = ({ signal }) =>
    getConsumptions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getConsumptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConsumptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getConsumptions>>>;

export type GetConsumptionsQueryError = ErrorType<unknown>;

export function useGetConsumptions<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConsumptions>>,
          TError,
          Awaited<ReturnType<typeof getConsumptions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetConsumptions<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConsumptions>>,
          TError,
          Awaited<ReturnType<typeof getConsumptions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetConsumptions<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 월별 소비내역 무한스크롤 조회
 */

export function useGetConsumptions<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetConsumptionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetConsumptionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetConsumptionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConsumptions>>> = ({ signal }) =>
    getConsumptions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getConsumptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConsumptionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConsumptions>>
>;

export type GetConsumptionsSuspenseQueryError = ErrorType<unknown>;

export function useGetConsumptionsSuspense<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetConsumptionsSuspense<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetConsumptionsSuspense<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 월별 소비내역 무한스크롤 조회
 */

export function useGetConsumptionsSuspense<
  TData = Awaited<ReturnType<typeof getConsumptions>>,
  TError = ErrorType<unknown>,
>(
  params: GetConsumptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getConsumptions>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetConsumptionsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetSharedPersonaCardQueryOptions = <
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSharedPersonaCardQueryKey(shareToken);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSharedPersonaCard>>> = ({ signal }) =>
    getSharedPersonaCard(shareToken, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: shareToken !== null && shareToken !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetSharedPersonaCardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSharedPersonaCard>>
>;

export type GetSharedPersonaCardQueryError = ErrorType<unknown>;

export function useGetSharedPersonaCard<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSharedPersonaCard>>,
          TError,
          Awaited<ReturnType<typeof getSharedPersonaCard>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSharedPersonaCard<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSharedPersonaCard>>,
          TError,
          Awaited<ReturnType<typeof getSharedPersonaCard>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSharedPersonaCard<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 공유받은 취향카드 조회
 */

export function useGetSharedPersonaCard<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSharedPersonaCardQueryOptions(shareToken, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetSharedPersonaCardSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSharedPersonaCardQueryKey(shareToken);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSharedPersonaCard>>> = ({ signal }) =>
    getSharedPersonaCard(shareToken, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getSharedPersonaCard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSharedPersonaCardSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSharedPersonaCard>>
>;

export type GetSharedPersonaCardSuspenseQueryError = ErrorType<unknown>;

export function useGetSharedPersonaCardSuspense<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSharedPersonaCardSuspense<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSharedPersonaCardSuspense<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 공유받은 취향카드 조회
 */

export function useGetSharedPersonaCardSuspense<
  TData = Awaited<ReturnType<typeof getSharedPersonaCard>>,
  TError = ErrorType<unknown>,
>(
  shareToken: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSharedPersonaCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSharedPersonaCardSuspenseQueryOptions(shareToken, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetMonthlyReportQueryOptions = <
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMonthlyReportQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonthlyReport>>> = ({ signal }) =>
    getMonthlyReport(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMonthlyReport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMonthlyReportQueryResult = NonNullable<Awaited<ReturnType<typeof getMonthlyReport>>>;

export type GetMonthlyReportQueryError = ErrorType<unknown>;

export function useGetMonthlyReport<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthlyReport>>,
          TError,
          Awaited<ReturnType<typeof getMonthlyReport>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMonthlyReport<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthlyReport>>,
          TError,
          Awaited<ReturnType<typeof getMonthlyReport>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMonthlyReport<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 월간 리포트 조회
 */

export function useGetMonthlyReport<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMonthlyReportQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetMonthlyReportSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMonthlyReportQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonthlyReport>>> = ({ signal }) =>
    getMonthlyReport(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMonthlyReport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMonthlyReportSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMonthlyReport>>
>;

export type GetMonthlyReportSuspenseQueryError = ErrorType<unknown>;

export function useGetMonthlyReportSuspense<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMonthlyReportSuspense<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMonthlyReportSuspense<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 월간 리포트 조회
 */

export function useGetMonthlyReportSuspense<
  TData = Awaited<ReturnType<typeof getMonthlyReport>>,
  TError = ErrorType<unknown>,
>(
  params: GetMonthlyReportParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMonthlyReport>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMonthlyReportSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetCurrentStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentStatusQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentStatus>>> = ({ signal }) =>
    getCurrentStatus(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentStatus>>>;

export type GetCurrentStatusQueryError = ErrorType<unknown>;

export function useGetCurrentStatus<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentStatus>>,
          TError,
          Awaited<ReturnType<typeof getCurrentStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCurrentStatus<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentStatus>>,
          TError,
          Awaited<ReturnType<typeof getCurrentStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCurrentStatus<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 현재 리포트 현황 조회
 */

export function useGetCurrentStatus<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentStatusQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetCurrentStatusSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentStatusQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentStatus>>> = ({ signal }) =>
    getCurrentStatus(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCurrentStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentStatusSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentStatus>>
>;

export type GetCurrentStatusSuspenseQueryError = ErrorType<unknown>;

export function useGetCurrentStatusSuspense<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCurrentStatusSuspense<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetCurrentStatusSuspense<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 현재 리포트 현황 조회
 */

export function useGetCurrentStatusSuspense<
  TData = Awaited<ReturnType<typeof getCurrentStatus>>,
  TError = ErrorType<unknown>,
>(
  params: GetCurrentStatusParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentStatusSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetFrequentPlacesQueryOptions = <
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFrequentPlacesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFrequentPlaces>>> = ({ signal }) =>
    getFrequentPlaces(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFrequentPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFrequentPlacesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFrequentPlaces>>
>;

export type GetFrequentPlacesQueryError = ErrorType<unknown>;

export function useGetFrequentPlaces<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetFrequentPlacesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFrequentPlaces>>,
          TError,
          Awaited<ReturnType<typeof getFrequentPlaces>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetFrequentPlaces<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFrequentPlaces>>,
          TError,
          Awaited<ReturnType<typeof getFrequentPlaces>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetFrequentPlaces<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 자주 소비한 곳 랭킹 무한스크롤 조회
 */

export function useGetFrequentPlaces<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFrequentPlacesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetFrequentPlacesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFrequentPlacesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFrequentPlaces>>> = ({ signal }) =>
    getFrequentPlaces(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getFrequentPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFrequentPlacesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFrequentPlaces>>
>;

export type GetFrequentPlacesSuspenseQueryError = ErrorType<unknown>;

export function useGetFrequentPlacesSuspense<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetFrequentPlacesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetFrequentPlacesSuspense<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetFrequentPlacesSuspense<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

/**
 * @summary 자주 소비한 곳 랭킹 무한스크롤 조회
 */

export function useGetFrequentPlacesSuspense<
  TData = Awaited<ReturnType<typeof getFrequentPlaces>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFrequentPlacesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFrequentPlaces>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFrequentPlacesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
