/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import type {
  GetConsumptionsParams,
  GetCurrentStatusParams,
  GetFrequentPlacesParams,
  GetMonthlyReportParams,
} from '@/features/report/apis/dto';

export const getGetConsumptionsQueryKey = (params?: GetConsumptionsParams) => {
  return [`/consumptions`, ...(params ? [params] : [])] as const;
};

export const getGetMonthlyReportQueryKey = (params?: GetMonthlyReportParams) => {
  return [`/reports/monthly`, ...(params ? [params] : [])] as const;
};

export const getGetCurrentStatusQueryKey = (params?: GetCurrentStatusParams) => {
  return [`/reports/current`, ...(params ? [params] : [])] as const;
};

export const getGetFrequentPlacesQueryKey = (params?: GetFrequentPlacesParams) => {
  return [`/consumptions/places/rank`, ...(params ? [params] : [])] as const;
};
