/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type {
  ApiResponseNearbyPlacesResponse,
  ApiResponsePlaceLikeResponse,
  ApiResponseVisitedPlaceMarkerResponse,
  GetNearbyPlacesParams,
  GetVisitedPlaceMarkersParams,
  SecondParameter,
} from '@/features/map/apis/dto';

/**
 * 좋아요 상태를 등록하고 취소한다
 * @summary 가게 좋아요 토글
 */
export const toggleLike = (
  placeId: number,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponsePlaceLikeResponse>(
    { url: `/places/${placeId}/likes`, method: 'PUT', signal },
    options
  );
};

/**
 * 지도 중심 좌표 반경 안의 인기 가게를 조회. myTownPlaces는 전체 인기순, sameCategoryPlaces는 내가 가장 많이 방문한 카테고리로 필터링한 결과로 둘 중 중복된건 1개만 응 답
 * @summary 내 주변 가게 추천
 */
export const getNearbyPlaces = (
  params: GetNearbyPlacesParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseNearbyPlacesResponse>(
    { url: `/recommendations/nearby-places`, method: 'GET', params, signal },
    options
  );
};

/**
 * 현재 사용자가 소비기록을 남긴 장소 전체를 위경도 좌표와 함께 조회합니다. 페이지네이션 없이 전체 목록을 반환합니다 categories 파라미터로 특정 카테고리만 필터링할 수 있습니다.
 * @summary 홈 화면 지도용 방문 장소 마커 조회
 */
export const getVisitedPlaceMarkers = (
  params?: GetVisitedPlaceMarkersParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseVisitedPlaceMarkerResponse>(
    { url: `/consumptions/visited-places`, method: 'GET', params, signal },
    options
  );
};
