/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

export type PlaceLikeResponse = {
  liked?: boolean;
};

export type ApiResponsePlaceLikeResponse = {
  code?: string;
  message?: string;
  data?: PlaceLikeResponse;
};

export type RecommendedPlaceItem = {
  placeId?: number;
  name?: string;
  dongName?: string;
  category?: string;
  latitude?: number;
  longitude?: number;
  visitCount?: number;
  liked?: boolean;
  thumbnailUrl?: string;
  googleMapsUri?: string;
};

export type NearbyPlacesResponse = {
  myTownPlaces?: RecommendedPlaceItem[];
  sameCategoryPlaces?: RecommendedPlaceItem[];
};

export type ApiResponseNearbyPlacesResponse = {
  code?: string;
  message?: string;
  data?: NearbyPlacesResponse;
};

export type VisitedPlaceMarkerItem = {
  placeId?: number;
  placeName?: string;
  category?: string;
  latitude?: number;
  longitude?: number;
  visitCount?: number;
  liked?: boolean;
  stickerCategory?: string;
  stickerName?: string;
  googlePlaceId?: string;
};

export type VisitedPlaceMarkerResponse = {
  places?: VisitedPlaceMarkerItem[];
  month?: number;
  monthlyPlaceCount?: number;
};

export type ApiResponseVisitedPlaceMarkerResponse = {
  code?: string;
  message?: string;
  data?: VisitedPlaceMarkerResponse;
};

export type GetNearbyPlacesParams = {
  /**
   * 위도
   */
  lat: number;
  /**
   * 경도
   */
  lng: number;
  /**
   * 검색 반경(미터), 생략시 1500m / 위치기반이면 적정범위 500m~1km
   */
  radiusMeters?: number;
};

export type GetVisitedPlaceMarkersParams = {
  /**
   * 필터링할 카테고리 (생략시 전체 카테고리)
   */
  categories?: string[];
};

export type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
