/**
 * Generated by Orval and split by scripts/split-openapi-output.mjs.
 * Do not edit manually.
 */

import { apiClient } from '@/shared/apis/orvalMutator';

import type { BodyType } from '@/shared/apis/orvalMutator';

import type {
  ApiResponseConsumptionCreateResponse,
  ApiResponseReceiptOcrResponse,
  ConsumptionCreateRequest,
  ReceiptOcrRequest,
  SecondParameter,
} from '@/features/record/api/dto';

/**
 * 사용자가 확인한 장소와 소비 정보를 최종 저장합니다.
 *
 * Google Place ID가 이미 등록된 장소라면 기존 장소를 재사용합니다.
 *
 * 신규 장소라면 도로명주소를 SGIS로 조회해 행정동을 저장합니다.
 *
 * receiptImageId는 영수증 OCR을 사용한 경우에만 전달합니다.
 * @summary 소비 기록 등록
 */
export const createConsumption = (
  consumptionCreateRequest: BodyType<ConsumptionCreateRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  return apiClient<ApiResponseConsumptionCreateResponse>(
    {
      url: `/consumptions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: consumptionCreateRequest,
      signal,
    },
    options
  );
};

/**
 * 영수증 이미지를 OCR 처리하고 사용자가 확인·수정할 인식 결과를 반환합니다.
 *
 * 인식하지 못한 항목은 null로 반환됩니다.
 * @summary 영수증 OCR 요청
 */
export const recognizeReceipt = (
  receiptOcrRequest?: BodyType<ReceiptOcrRequest>,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  if (receiptOcrRequest?.receiptImage !== undefined) {
    formData.append(`receiptImage`, receiptOcrRequest.receiptImage);
  }

  return apiClient<ApiResponseReceiptOcrResponse>(
    {
      url: `/consumptions/receipt-ocr`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  );
};
